name: mobile_detailing_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  intl: ^0.19.0
  geolocator: ^12.0.0
  weather: ^3.1.1
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  jiffy: ^6.3.1
  table_calendar: ^3.1.2
  badges: ^3.1.2
  flutter_inappwebview: ^6.0.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  shared_preferences: ^2.3.2
  calendar_view: ^1.2.0
  fl_chart: ^0.69.0
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/nclogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/nclogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/nclogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/nclogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#001F3F"
  image: assets/images/n&clogo.png
  android_12: 
    image: assets/images/n&clogo12.png
    color: "#001F3F"
  android: true
  ios: true
