// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYuu-GFE1Xx5hM6Rb66N-2Q6KkZrwQ5wU',
    appId: '1:1030190362045:web:6980270b30e271b7ac36d4',
    messagingSenderId: '1030190362045',
    projectId: 'nook-and-cranny-admin-app',
    authDomain: 'nook-and-cranny-admin-app.firebaseapp.com',
    storageBucket: 'nook-and-cranny-admin-app.appspot.com',
    measurementId: 'G-GHC7P9ZY0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9RneBftKWH8YiAAacjXhryn4J-3l-sNM',
    appId: '1:1030190362045:android:9407ba6dfa32ce09ac36d4',
    messagingSenderId: '1030190362045',
    projectId: 'nook-and-cranny-admin-app',
    storageBucket: 'nook-and-cranny-admin-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuu84NuZy6MzBQ8UsmwMV3XVpq1cmbJzc',
    appId: '1:1030190362045:ios:b56c6ef454ef47a7ac36d4',
    messagingSenderId: '1030190362045',
    projectId: 'nook-and-cranny-admin-app',
    storageBucket: 'nook-and-cranny-admin-app.appspot.com',
    iosClientId: '1030190362045-ee9cdnvcd4irri3khv7jjmbajj0nkoft.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileDetailingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuu84NuZy6MzBQ8UsmwMV3XVpq1cmbJzc',
    appId: '1:1030190362045:ios:b56c6ef454ef47a7ac36d4',
    messagingSenderId: '1030190362045',
    projectId: 'nook-and-cranny-admin-app',
    storageBucket: 'nook-and-cranny-admin-app.appspot.com',
    iosClientId: '1030190362045-ee9cdnvcd4irri3khv7jjmbajj0nkoft.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileDetailingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYuu-GFE1Xx5hM6Rb66N-2Q6KkZrwQ5wU',
    appId: '1:1030190362045:web:89ea308d4bec569eac36d4',
    messagingSenderId: '1030190362045',
    projectId: 'nook-and-cranny-admin-app',
    authDomain: 'nook-and-cranny-admin-app.firebaseapp.com',
    storageBucket: 'nook-and-cranny-admin-app.appspot.com',
    measurementId: 'G-HTH2G2KCJ9',
  );
}
